platform :ios, '7.0'

inhibit_all_warnings!

pod 'AHAlertView'
pod 'Mixpanel', '~> 2.3.6'
pod 'Foursquare-iOS-API', '~> 2.0'
pod 'AFNetworking', '~> 1.2'
pod 'SDWebImage', '~> 3.7'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'BSKeyboardControls', '~>2.0'
pod 'BlocksKit', '~>2.2.5'
pod 'MBProgressHUD'
pod 'MSDynamicsDrawerViewController', '~>1.0.0'
pod 'FormatterKit'
pod 'UIView+Positioning'
pod 'CrittercismSDK'
pod 'Braintree', '~> 3.9'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Kochava'
pod 'ActionSheetPicker-3.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'SendBirdSDK'