//user defaults keys
#define kDefaultsKeyName @"defaultsKeyName"
#define kDefaultsFirstName @"defaultsKeyFirstName"
#define kDefaultsLastName @"defaultsKeyLastName"
#define kDefaultsKeyEmail   @"defaultsKeyEmail"
#define kDefaultsKeyPhone   @"defaultsKeyPhone"
#define kDefaultsKeyFacebookID @"defaultsKeyFacebookID"
#define kDefaultsKeyIsLoggedIn @"defaultsKeyIsLoggedIn"
#define kDefaultsKeyLastAuthorizationToken @"lastAuthorizationToken"
